# Generated by Django 5.2.17 on 2026-10-05 16:52

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #1A2B3C.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='unique_category_name_per_owner')],
            },
        ),
    ]
